### ISSUE TITLE
Documentation: Would like to get an example file for the LDAP/AD configuraiton

### ISSUE THREAD

**Issue by qubusp** [ninech/netbox-docker#102]
Documentation: Would like to get an example file for the LDAP/AD configuraiton

**Comment by cimnine** [comment]
The default configuration that comes with `netbox-docker-ldap` is in [configuration/ldap_config.py](https://github.com/ninech/netbox-docker/blob/master/configuration/ldap_config.py).

The meaning of each setting is described in the [official Netbox documentation](https://netbox.readthedocs.io/en/latest/installation/4-ldap/).

Feel free to create a PR if [the current documentation on LDAP](https://github.com/ScanPlusGmbH/netbox-docker/blob/master/README.md#ldap-enabled-variant) was missing something relevant for you, but I believe a sample config is out of scope.
