### ISSUE TITLE
Change default page size to 1000

### ISSUE THREAD

**Issue by tyler-8** [ninech/netbox-docker#105]
## Current Behavior

[env/netbox.env](https://github.com/ninech/netbox-docker/blob/d8285b05f254163de9d883a63a3c102b072e1e89/env/netbox.env#L15) defines `MAX_PAGE_SIZE=0`, effectively disabling API pagination.

## Expected Behavior

The [documented default pagesize](https://netbox.readthedocs.io/en/stable/configuration/optional-settings/#max_page_size) of Netbox is 1000. I'd recommend setting the same number out of the box, or just not set the variable at all. This is a common pattern for performance reasons and may (like it did for me initially) lead to some confusion on why the pagination didn't seem be limiting results by default.

I realize that those environment settings are really just there for quick testing and any 'real' deployment should override pretty much every setting in that file. It's a minor change, but thought it could be helpful as it was confusing some of my peers who are testing Netbox now.

**Comment by bdlamprecht** [comment]
I've got no issues with this change, makes sense to me.
