### ISSUE TITLE
Build fails on Fedora 29 with SELinux enabled

### ISSUE THREAD

**Issue by ViktorBarzin** [ninech/netbox-docker#110]
## Current Behavior

`docker-compose up` fails with SELinux enabled.

I am using latest Fedora (29) with SELinux enabled and running `docker-compose up` fails with a permission denied error. Full logs can be seen [here](http://paste.ubuntu.com/p/sDmrzvH2nB/)

## Expected Behavior

I expected a successful build.

## Debug Information

The output of `docker-compose version`: `1.22.0, build f46880f`
The output of `docker version`: `1.13.1, build accfe55-unsupported`
The output of `git rev-parse HEAD`: `eb09bf53644f057664437b5a473341a8e4491698`
The command you used to start the project: `docker-compose up`

## Temporary solution
Disabling SELinux fixes the issue but this is not a desirable solution

**Comment by cimnine** [comment]
Thank you for your report. It is unfortunately not possible for this project to influence your local SELinux configuration. Please make sure, that you configure SELinux in such a way, that Docker volumes are writable from inside all containers, to which that volume is attached to.
