### ISSUE TITLE
Promote this repo as the primary Docker build for NetBox

### ISSUE THREAD

**Issue by jeremystretch** [ninech/netbox-docker#12]
The "official" [NetBox Docker repo](https://github.com/digitalocean/netbox-docker) never went anywhere. I'd like to designate this project as the primary source for Docker builds. Aside from updating the link in the README and decommissioning the original repo, is there anything I can assist with?

**Comment by cimnine** [comment]
Thanks @jeremystretch !

My only concern is how to proceed with the `digitalocean/netbox-docker` repository on Github and the `digitalocean/netbox` repository on Docker hub. Should they go away to not confuse people? Should they stay for historical purpose? I'm hesitant and I'd be interested in your thoughts.

**Comment by jeremystretch** [comment]
I'll destroy the `digitalocean/netbox-docker` repo. I need to track down someone with admin access to `digitalocean/netbox` on Docker hub but we'll ditch that too.

**Comment by cimnine** [comment]
Great! Feel free to link to this repository anytime and I'll be doing my best to keep this Docker image of Netbox working.
