### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by coxdjustin** [ninech/netbox-docker#13]
I just did the default installation and only get a 502 Bad Gateway error when trying to connect.

echo "http://$(docker-compose port nginx 80)/"                                                                
http://0.0.0.0:32768/
open "http://$(docker-compose port nginx 80)/"

**Comment by jeromeb42** [comment]
Hello,

Same for me but I have this log, configuration file is missing ?

netbox_1    | Traceback (most recent call last):
netbox_1    |   File "/opt/netbox/netbox/netbox/settings.py", line 9, in <module>
netbox_1    |     from netbox import configuration
netbox_1    | ImportError: cannot import name 'configuration'
netbox_1    |
netbox_1    | During handling of the above exception, another exception occurred:
netbox_1    |
netbox_1    | Traceback (most recent call last):
netbox_1    |   File "./manage.py", line 10, in <module>
netbox_1    |     execute_from_command_line(sys.argv)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
netbox_1    |     utility.execute()
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
netbox_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 206, in fetch_command
netbox_1    |     klass = load_command_class(app_name, subcommand)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 40, in load_command_class
netbox_1    |     module = import_module('%s.management.commands.%s' % (app_name, name))
netbox_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
netbox_1    |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
netbox_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
netbox_1    |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
netbox_1    |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
netbox_1    |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
netbox_1    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 15, in <module>
netbox_1    |     from django.db.migrations.autodetector import MigrationAutodetector
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/autodetector.py", line 13, in <module>
netbox_1    |     from django.db.migrations.questioner import MigrationQuestioner
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/questioner.py", line 12, in <module>
netbox_1    |     from .loader import MigrationLoader
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 10, in <module>
netbox_1    |     from django.db.migrations.recorder import MigrationRecorder
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 12, in <module>
netbox_1    |     class MigrationRecorder(object):
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 26, in MigrationRecorder
netbox_1    |     class Migration(models.Model):
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 27, in Migration
netbox_1    |     app = models.CharField(max_length=255)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1061, in __init__
netbox_1    |     super(CharField, self).__init__(*args, **kwargs)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 172, in __init__
netbox_1    |     self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
netbox_1    |     self._setup(name)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
netbox_1    |     self._wrapped = Settings(settings_module)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
netbox_1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
netbox_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
netbox_1    |     return _bootstrap._gcd_import(name[level:], package, level)
netbox_1    |   File "/opt/netbox/netbox/netbox/settings.py", line 12, in <module>
netbox_1    |     "Configuration file is not present. Please define netbox/netbox/configuration.py per the documentation."
netbox_1    | django.core.exceptions.ImproperlyConfigured: Configuration file is not present. Please define netbox/netbox/configuration.py per the documentation.
netbox_1    | Traceback (most recent call last):
netbox_1    |   File "/opt/netbox/netbox/netbox/settings.py", line 9, in <module>
netbox_1    |     from netbox import configuration
netbox_1    | ImportError: cannot import name 'configuration'

**Comment by cimnine** [comment]
@jeromeb42 this has been fixed in #14, but I suspect what @coxdjustin describes to be a different issue.

**Comment by cimnine** [comment]
There are now also build on Docker hub for the latest fix.

**Comment by jeromeb42** [comment]
Hello, thanks for your help.

It's better now.
I do a git pull + docker pull ninech/netbox
After a docker-compose down then docker-compose up I have the 3 container up&running but I have a 400 bad request when I try to access to the web interface.

As I can see nothing bad on the log files.
Did you have an idea?
