### ISSUE TITLE
compose is version 3, but seems to be version 2 compatible

### ISSUE THREAD

**Issue by jkrauska** [ninech/netbox-docker#15]
I have some older boxes with docker 1.10, which only supports compose version 2.

Current docker-compose.yml file lists the version at '3', but seems to be fully backward compatible with '2'.
https://github.com/ninech/netbox-docker/blob/master/docker-compose.yml#L1

Features between 2 and 3 are listed here.
https://docs.docker.com/compose/compose-file/compose-versioning/#version-21
I didn't see any features > 2 in use.

I'd done compose up with no issues on a 1.10 docker box and this single line change.
✅ Finished building the Docker images 'ninech/netbox:v2.2.1'

I'd like to propose that you only limit compose file version to the minimal needed to meet the parameters in use -- to ensure wider compatibility.

Single digit change.

**Comment by cimnine** [comment]
When I change the version to `'2'` and `docker-compose pull`, I get an error.

```
$ dc pull                                                       
ERROR: Invalid interpolation format for "image" option in service "netbox": "ninech/netbox:${BRANCH-latest}"
```

**Comment by rowanruseler** [comment]
@cimnine You can resolve that by removing line 5:6, and changing image to "ninech/netbox:latest"

**Comment by cimnine** [comment]
This is correct, but I don't want to change the implementation as is.
The current implementation provides a simple way to define which version of Netbox to use without touching the docker-compose file. Whereas with the change you propose this would not be possible anymore.

**Comment by cimnine** [comment]
I have written documentation about the use-case of the build variable: https://github.com/ninech/netbox-docker/pull/17
