### ISSUE TITLE
Moving to your docker I can't restore

### ISSUE THREAD

**Issue by RyanD0001** [ninech/netbox-docker#18]
Hi,

I was running netbox 2.1.6 and I moved to your build but i'm now not un able to restore my db backup do you have a 2.1.6 version?

Thanks

**Comment by cimnine** [comment]
Sure, there is a tag for `2.1.6` on [hub.docker.com](https://hub.docker.com/r/ninech/netbox/tags/).

If you're launching with docker-compose, [follow the guide in the README.md](https://github.com/ninech/netbox-docker#version) to launch a specific version.
