### ISSUE TITLE
Allowed_hosts format

### ISSUE THREAD

**Issue by LBegnaud** [ninech/netbox-docker#20]
I played around with this a bit

We have a single reverse proxy for our internal sites so I brought up a separate VM, built out this three-container setup and got it working. I then ran into some issues trying to have it accessible from behind the second layer of nginx. What I found was that I had no idea how to set the environment variable for `ALLOWED_HOSTS` to include a space to set multiple values

If you know of a way to do that, including it in the example would be nice. If it's not possible, might I suggest using a comma to separate multiple allowed hosts? The netbox `configuration.py` file defines 

```
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(' ')
```

Perhaps we can adjust that to be

```
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
```

And change the example env file to show off this capability

```
ALLOWED_HOSTS=localhost,127.0.0.1
```

And finally, a note somewhere in the project about setting the `Host` header to be `$http_host`?

**Comment by cimnine** [comment]
I don't quite understand what the problem with space-separated lists is. Could you explain this further?

`$http_host` is a feature of Nginx and thous [documented in Nginx's documentation][nginx_http]. What kind of note would you have expected to find in this project? (IMO it's just normal behaviour that the `Host`-header is forwarded when reverse-proxying.)

[nginx_http]: http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_

**Comment by LBegnaud** [comment]
I couldn't get the env file to define multiple allowed hosts. 

Testing this morning it appears to work just fine so I suppose this was just a case of poor assumptions.

As for the Host header, this i believe would be more useful. Netbox presents a pretty unuseful error 400 if the host header is not in the allowed hosts list. 

Without setting the Host header specifically it seems to use whatever nginx is using for the proxy_pass host. 

I'm just commenting on the issues I ran into while getting this set up. Thanks for taking the time to make it this easy to deploy netbox!
