### ISSUE TITLE
Running into an exit 1 code on nginx and netbox

### ISSUE THREAD

**Issue by rpmirish12** [ninech/netbox-docker#22]
On compose up i get the following output running docker in windows:

```nginx_1     | 2017/11/22 04:26:48 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx_1     | nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx_1     | 2017/11/22 04:29:58 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx_1     | nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
postgres_1  | The files belonging to this database system will be owned by user "postgres".
netbox_1    | standard_init_linux.go:185: exec user process caused "no such file or directory"
postgres_1  | This user must also own the server process.
netbox_1    | standard_init_linux.go:185: exec user process caused "no such file or directory"
```

It looks like nginx exits due the netbox host not being found, while netbox fails due to a missing directory. Thoughts?

**Comment by cimnine** [comment]
Please provide some more information:

* The output of `docker-compose version`
* The output of `docker version`
* The output of `git rev-parse HEAD`
* The command you launched to start the project

**Comment by Preskton** [comment]
Hi, I'm encountering the same issue, also on Windows.

- The output of `docker-compose version` --> `docker-compose version 1.16.1, build 6d1ac219`
- The output of `docker version` --> `Docker version 17.09.0-ce, build afdb6d4`
- The output of `git rev-parse HEAD` --> `e4ddfc925ca439beaed64385cf7bc28bff6a16b9`
- The command you launched to start the project:

```
❯ docker-compose up -d

netboxdocker_postgres_1 is up-to-date
Starting netboxdocker_netbox_1 ...
Starting netboxdocker_netbox_1 ... done
Starting netboxdocker_nginx_1 ...
Starting netboxdocker_nginx_1 ... done

❯ docker-compose port nginx 80
ERROR: No container found for nginx_1
```

### Logs from `netboxdocker_nginx_1`:

```
2017/12/01 04:23:21 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
2017/12/01 06:30:01 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
2017/12/01 06:31:37 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
2017/12/01 06:31:39 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:28
```

### Logs from `netboxdocker_netbox_1`:

```
standard_init_linux.go:185: exec user process caused "no such file or directory"
standard_init_linux.go:185: exec user process caused "no such file or directory"
```

Thanks in advance.

pd

**Comment by cimnine** [comment]
Did you build the image or pull it from Docker Hub? Can you run `docker-compose pull`?

It looks like you ran into line encoding issues: https://forums.docker.com/t/standard-init-linux-go-175-exec-user-process-caused-no-such-file/20025/4

**Comment by cimnine** [comment]
I haven't heard back in almost a week, so I'll close this now.

**Comment by cmchuron** [comment]
I'm also having this issue, running on Windows (runs fine in Linux.)
I've taken the steps above in this string, and while I suspect you're right, it relates to the line encoding issues, I don't know how to fix it, or which files are causing the problem.

c:\Docker\netbox-docker>docker-compose --version
docker-compose version 1.22.0, build f46880fe

c:\Docker\netbox-docker>docker --version
Docker version 18.06.1-ce, build e68fc7a

c:\Docker\netbox-docker>git rev-parse HEAD
f1ebd4d24634a996a7404b2bba7de37cd7631b8e

c:\Docker\netbox-docker>docker-compose logs -f nginx
Attaching to netbox-docker_nginx_1
nginx_1          | 2018/10/04 19:05:39 [emerg] 1#1: host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:29
nginx_1          | nginx: [emerg] host not found in upstream "netbox" in /etc/netbox-nginx/nginx.conf:29
netbox-docker_nginx_1 exited with code 1

c:\Docker\netbox-docker>docker-compose ps
The system cannot find the path specified.
            Name                           Command               State     Ports
----------------------------------------------------------------------------------
netbox-docker_netbox-worker_1   python3 /opt/netbox/netbox ...   Up
netbox-docker_netbox_1          /opt/netbox/docker-entrypo ...   Exit 1
netbox-docker_nginx_1           nginx -c /etc/netbox-nginx ...   Exit 1
netbox-docker_postgres_1        docker-entrypoint.sh postgres    Up       5432/tcp
netbox-docker_redis_1           docker-entrypoint.sh sh -c ...   Up       6379/tcp

**Comment by cmchuron** [comment]
Update:  I opened and saved the Dockefile and docker-compose.yml files in notepod++, and issue is resolved.
