### ISSUE TITLE
No assets loading

### ISSUE THREAD

**Issue by kyleratti** [ninech/netbox-docker#31]
## Current Behavior

Netbox is set up via the docker instance and I am loading the home/index page for the first time but all of the assets (css/js) give a 404

## Expected Behavior

The assets to give a 200 and actually be served

## Debug Information

The output of `docker-compose version`: `docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016`
The output of `docker version`: `Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false`

`stdout`: https://gist.github.com/kyleratti/4c4add3ee72b4ef8bbbd05cd907996d3
`stderr`: https://gist.github.com/kyleratti/85389a5ca5861c52c107859b97f5d263

![netbox-error](https://user-images.githubusercontent.com/4738168/34499799-c3157210-efd5-11e7-8391-1508a1ff66ea.png)

**Comment by cimnine** [comment]
It seems you are accessing the Netbox container directly and not via nginx. This is not supported by netbox-docker, and also not the [recommended way of installing netbox](https://netbox.readthedocs.io/en/latest/installation/web-server/).

Can you please post the url from the browser and the output of `docker-compose ps`?
