### ISSUE TITLE
Is there a way to NOT use ephemeral ports on startup?

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#32]
## Current Behavior
This may be a very basic docker question, but I can't seem to find the documentation to answer this question...

Currently, my default, the netbox application proxied by ngnix is available on port 32768:
```
$ docker-compose up -d
Creating network "netbox_default" with the default driver
Creating volume "netbox_netbox-nginx-config" with local driver
Creating volume "netbox_netbox-static-files" with local driver
Creating volume "netbox_netbox-report-files" with local driver
Creating volume "netbox_netbox-media-files" with local driver
Creating netbox_postgres_1 ...
Creating netbox_postgres_1 ... done
Creating netbox_netbox_1 ...
Creating netbox_netbox_1 ... done
Creating netbox_nginx_1 ...
Creating netbox_nginx_1 ... done

$ echo "http://$(docker-compose port nginx 8080)/"
http://0.0.0.0:32768/
```
Each time you do a `docker-compose down` followed up `docker-compose up` -d the application is exposed on a different port (initial +1):
```
$ docker-compose down
Stopping netbox_nginx_1    ... done
Stopping netbox_netbox_1   ... done
Stopping netbox_postgres_1 ... done
Removing netbox_nginx_1    ... done
Removing netbox_netbox_1   ... done
Removing netbox_postgres_1 ... done
Removing network netbox_default

$ docker-compose up -d
Creating network "netbox_default" with the default driver
Creating netbox_postgres_1 ...
Creating netbox_postgres_1 ... done
Creating netbox_netbox_1 ...
Creating netbox_netbox_1 ... done
Creating netbox_nginx_1 ...
Creating netbox_nginx_1 ... done

$ echo "http://$(docker-compose port nginx 8080)/"
http://0.0.0.0:32769/
```

## Expected Behavior
The question at hand is whether you can bind the application to a specific port number each time you the application is built / run (ephemeral port range or not)?

## Debug Information
N/A

**Comment by bdlamprecht** [comment]
I don't know why I didn't figure this out previously, but my simply altering line 23 of of the  `docker-compose.yml` file from:
https://github.com/ninech/netbox-docker/blob/52e653dd303a98b3fd9693863581095407ec3a19/docker-compose.yml#L23
to look like
```
        - 10123:8080
```
It appears to have solved the problem.

As a suggestion, you may want to document that in the `README.md` as I would assume others *could* run into the same question as I did.

Sorry for issue for the somewhat basic question on docker.

**Comment by cimnine** [comment]
The port configuration is ephemeral on purpose. It allows us to launch multiple instances of Netbox at the same time without port conflicts.

But we developed a tool called [reception](https://github.com/ninech/reception) which helps us deal with the ever-changing port names using a clever combination of DNS and reverse-proxying.
