### ISSUE TITLE
os.getenv gets NAPALM_TIMEOUT as str, should be int to work with the network driver

### ISSUE THREAD

**Issue by moronbros** [ninech/netbox-docker#36]
## Current Behavior

After a `pip install napalm` with the proper environment variables set to make a napalm network driver for EOS, the buttons in the netbox GUI for LLDP/status/running config came alive, as expected. Clicking on those buttons executes napalm code, but the function used to make the network driver pulls in NAPALM_TIMEOUT from the environment. I had this variable set to '10' in the shell. os.getenv() returns a string though, and when it feeds a string of '10' into the napalm device/driver and you call device.open() on it, it will detonate with:

"{"detail":"Error connecting to the device at 192.168.1.34: an integer is required (got type str)”}”

This error is bubbled all the way up to the GUI and presented to the end user as a modal.

The netbox code in views.py is catching Exception and just slapping the type error in the raised error message. This isn't incredibly helpful, but I can see he has a #TODO to make the error-handing a little better here.

## Expected Behavior

When we pull the environment variable out of the shell and into python, it should be cast into an int so napalm doesn't, so to speak, light on fire.

## Debug Information
I didn't catch the logs before I fixed the issue locally, but I do have information about my environment.

```
$ docker-compose version
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

$ docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ git rev-parse HEAD
52e653dd303a98b3fd9693863581095407ec3a19
```

**Comment by cimnine** [comment]
Thanks for reporting this issue. Could you test the changes in #38?

**Comment by moronbros** [comment]
The changes look good. I was able to use the timeout I had set in my environment without error from napalm. Thanks!
