### ISSUE TITLE
Latest Version Doesn't Have Icons (from Bootstrap)

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#42]
## Current Behavior

After cloning this latest revision in an attempt to test out the loading of "custom fields when creating the container" feature, I noticed something really strange.

With this latest version, the small icons for adding / exporting objects (`Sites`, `Regions`, `Devices`, etc) don't appear anymore.  I think it may have something to do with the volume `netbox-static-files` but am not positive.

Current commit:
![image](https://user-images.githubusercontent.com/7783306/35651373-b8bb7912-069c-11e8-96af-07cb13362027.png)

...

## Expected Behavior
Previous commits:
![image](https://user-images.githubusercontent.com/7783306/35651403-d4f9313c-069c-11e8-833a-8b7ac37b3e00.png)

...

## Debug Information

The output of `docker-compose version`: 1.17.1, build 6d101fb
The output of `docker version`: `17.05.0-ce, build 89658be`
The output of `git rev-parse HEAD`: `d2ec32fefe46fe61307df832491b31fac7b5ae7c`
The command you used to start the project: `docker-compose up -d`

The output of `docker-compose logs netbox`:

```
I don't see anything odd, but I can provide if needed.
```

The output of `docker-compose logs nginx`:

```
Attaching to netboxdocker_nginx_1
```

**Comment by bdlamprecht** [comment]
After further exploration, it seems once you login to NetBox as the a user (default is `admin`), those bootstrap icons **DO** appear.

Once you logout though, they disappear once again.

**Comment by cimnine** [comment]
Pretty sure that's expected behaviour. Because you can't add models or import data when you're just a guest.
