### ISSUE TITLE
FR: Add LDAP Support for "Dockerized" NetBox

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#49]
## Current Behavior
Querying against an available LDAP server doesn't work as the python library `django-auth-ldap` isn't installed.

I was able to add it myself and get it working and am happy to work on a PR, however, I didn't want to spend time if you weren't going to plan on adding support for that feature in this repository.
...

## Expected Behavior
I added the following lines in the `Dockerfile`:
```
RUN pip install \
# gunicorn is used for launching netbox
      gunicorn \
# ruamel is used in startup_scripts
      ruamel.yaml \
# adding django-auth-ldap for ldap support
      django-auth-ldap
```
and
```
COPY docker/configuration.docker.py /opt/netbox/netbox/netbox/configuration.py
COPY docker/ldap_config.docker.py /opt/netbox/netbox/netbox/ldap_config.py
COPY docker/gunicorn_config.py /opt/netbox/
COPY docker/nginx.conf /etc/netbox-nginx/nginx.conf
COPY docker/docker-entrypoint.sh docker-entrypoint.sh
COPY startup_scripts/ /opt/netbox/startup_scripts/
COPY initializers/ /opt/netbox/initializers/
COPY configuration/configuration.py /etc/netbox/configuration.py
COPY configuration/ldap_config.py /etc/netbox/ldap_config.py
```
...

## Debug Information
N/A

**Comment by cimnine** [comment]
There is [already a PR][pr]. Feel free to check it out and add your comments. I'll close this issue in favour of the PR.

[pr]: https://github.com/ninech/netbox-docker/pull/48
