### ISSUE TITLE
How to support NAPALM_ARGS in netbox.env?

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#50]
## Current Behavior
I cannot connect to my Cisco devices via NAPALM as they require you to enter "privileged EXEC mode" AFTER initially logging into them.  This is [solved](http://napalm.readthedocs.io/en/latest/support/#optional-arguments) in the `NetworkDriver` of NAPALM by using the `optional_args` parameter.

NetBox has called this the `NAPALM_ARGS` and the [documented way](http://netbox.readthedocs.io/en/latest/configuration/optional-settings/#napalm_args) is to pass a `dict` with the needed values.

However, due to the way Docker interprets the values, it seems to escape the characters in a very strange manner.

I've tried several different ways and all have been unsuccessful.

## Expected Behavior
N/A

## Debug Information
In each of these attempts, they were all defined in the `netbox.env` file and the results were seen when connecting to the `netbox` container and looking at the environment variables.

---
Attempt 1:
```
NAPALM_ARGS={'secret':'password'}
```
Result 1:
```
NAPALM_ARGS='{'"'"'secret'"'"':'"'"'password'"'"'}'
```
---
Attempt 2:
```
NAPALM_ARGS=\{\'secret\'\:\'password\'\}
```
Result 2:
```
NAPALM_ARGS='\{\'"'"'secret\'"'"'\:\'"'"'password\'"'"'\}'
```
---
Attempt 3:
```
NAPALM_ARGS="{'secret':'password'}"
```
Result 3:
```
NAPALM_ARGS='"{'"'"'secret'"'"':'"'"'password'"'"'}"'
```
---
The closest result I was able to get was in...
Attempt 4:
```
NAPALM_ARGS={\"secret\":\"password\"}
```
Result 4:
```
NAPALM_ARGS='{\"secret\":\"password\"}'
```
---
I've done my best searching for ways to pass a python `dict` as an `ENV`, but no dice there either.
As someone who appears to have significant experience with Docker, I'm looking for suggestions on how to get this to function properly.

**Comment by cimnine** [comment]
An alternative to ENV is always mounting a config file into the container, respectively [building a new container on top of `ninech/netbox`][extend-container] containing your customized config file.

[extend-container]: https://github.com/ninech/netbox-docker/#custom-docker-image

**Comment by bdlamprecht** [comment]
Thanks for the idea.
After reading that I ended up adding the following lines to `netbox.env`:
```
NAPALM_ARGS1_KEY=secret
NAPALM_ARGS1_VALUE=password
