### ISSUE TITLE
Boolean variables in netbox.env turn into strings

### ISSUE THREAD

**Issue by arionl** [ninech/netbox-docker#56]
## Current Behavior

Boolean settings that are entered into `netbox.env` seem to turn into strings by `configuration.py`.

## Expected Behavior

`configuration.py` should ensure booleans are properly created. From what I can see, a reasonable way to do this would be to replace:

`DEBUG = os.environ.get('DEBUG', False)`

with:

`DEBUG = True if os.environ.get('DEBUG', False) == 'True' else False`

## Debug Information

For a `netbox.env` with `DEBUG=False`, here's how I saw the string issue:

```
root@container:/opt/docker/netbox# docker exec -i -t netbox_netbox_1 /bin/bash
bash-4.3# ./manage.py nbshell
### NetBox interactive shell (24c18369cd7f)
### Python 3.6.4 | Django 1.11.11 | NetBox 2.3.2
### lsmodels() will show available models. Use help(<model>) for more info.
>>> import netbox.settings
>>> help(netbox.settings)
Help on module netbox.settings in netbox:

NAME
    netbox.settings

DATA
    ADMINS = []
    ALLOWED_HOSTS = ['*']
    BANNER_BOTTOM = ''
    BANNER_LOGIN = ''
    BANNER_TOP = ''
    BASE_DIR = '/opt/netbox/netbox'
    BASE_PATH = ''
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ORIGIN_REGEX_WHITELIST = []
    CORS_ORIGIN_WHITELIST = ['']
    CSRF_TRUSTED_ORIGINS = ['*']
    DATABASE = {'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AG...
    DATABASES = {'default': {'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True,...
    DATA_UPLOAD_MAX_NUMBER_FIELDS = None
    DATETIME_FORMAT = 'N j, Y g:i a'
    DATE_FORMAT = 'N j, Y'
    DEBUG = 'False'
```

Notice that `DEBUG = 'False'` rather than `DEBUG = False`.

**Comment by cimnine** [comment]
Can you check [if the changes in the PR #57](https://github.com/ninech/netbox-docker/pull/57) would for you?

**Comment by arionl** [comment]
Confirmed that the fix is working for me. I rolled a new container and the boolean variables from the updated config file are being presented properly. Thanks!
