### ISSUE TITLE
allowed_hosts

### ISSUE THREAD

**Issue by FlorianHeigl** [ninech/netbox-docker#76]
* Have you looked through the issues already resolved?

yes, a similar one was closed

Ok, very simply put, the current mechanism of just returning a 400 error if the call is not sent to a target in the allowed hosts list should be re-considered.
As a new user I'll not pretend to know if there is any benefit as it is.
It feels useless in multiple aspects from a security point of view (since header based) and not authorizing the client but the destination), but much more than that it is an insane waste of time.
It can't be OK to just code to the point where the application throws a 400, call it "safe now" and walk off. Please make it do a **403** instead of just falling apart.

And since this has hit multiple people already it would be really good to at least think about it.
There's really no reason to assume one would be launching this on their desktop/laptop, either.
As is, I tried to the point of doing a socks-tunnel via ssh via firefox into the VM where the docker daemon is running, and even then it'll not work - but it works really fine using netcat, thank you for asking. I don't think this has the benefits you think :)

**Comment by chothomas** [comment]
I am new to netbox.  I have installed netbox successfully on Ubuntu 16.04, but trying to migrate to docker based netbox.   I having the 400 as well using ninech/netbox-docker.  Can you share what modifications you did to resolve the issue with "Allowed_Hosts" giving 400.  

BTW, I applaud him for the effort, but it seems the install and access in designed for one box.

ALLOWED_HOSTS=localhost 0.0.0.0 127.0.0.1 [::1] netbox nginx netboxdocker.docker nginx.netboxdocker.docker

**Comment by FlorianHeigl** [comment]
It has to completely match the URL you put in the browser. Including port.
I also had to deploy it in a single docker host, it would not come up via
swarm. But to be fair, if I had sufficient clue, I could fix that part. So
what I did was a SSH forward, I had tried with a socks dynamic one and one
for port 1234. Don't recall with one of was that worked. After creating a
few racks, hosts and links I had to stop for a while

Thomas Cho <notifications@github.com> schrieb am Do., 21. Juni 2018, 17:54:

**Comment by chothomas** [comment]
Thank you for your response.  I got lazy and changed to ALLOWED_HOSTS=['*'] and at least making some progress.  Instead of 400, now I am at 502 bad gateway which I would assume is the gunicorn issue... which is the same issue when I tried to create the docker netbox on my own without docker-decompose.

I will try one more day and if not going back to  almost giving up and going back to installing it on host.

**Comment by thde** [comment]
> It feels useless in multiple aspects from a security point of view (since header based) and not authorizing the client but the destination).

I can see your point here. The config itself is provided by Netbox:
https://netbox.readthedocs.io/en/stable/configuration/mandatory-settings/#allowed_hosts 

From my point of view it makes sense to have it in the docker image as well. But we could allow all hosts by default.

**Comment by FlorianHeigl** [comment]
Hi,

thanks for the good explanations.
I did not find the documentation back then, probably a doc link in the config file might be enough for total beginners. Whatever you think better :)

**Comment by thde** [comment]
In most cases the connection authorization will be done on container level. So it makes sense to me to allow all inside the container per default, as you can still change the settings.
