### ISSUE TITLE
Error when using "initializers/custom_fields.yml"

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#79]
## Current Behavior
With the recent change in `custom_fields.yml` from `filterable: true` to now be of the format `filter_logic: loose`, the container for `netbox_1` fails to start and errors out on the line for processing the file `20_custom_fields.py`

This can be quickly reproduced by cloning the current `master` branch and **un**-commenting out the lines for `integer_field` in the included example of `initializers/custom_fields.yml`

## Expected Behavior
The initializer script to correctly create the `custom_fields`

## Debug Information
The output of `docker-compose version`: `1.16.1`
The output of `docker version`: `18.01.0-ce`
The output of `git rev-parse HEAD`: `8333fafcf1c53ead35368d5b8fe73f9b7fa5b5ab`
The command you used to start the project: `docker-compose up`

The output of `docker-compose logs netbox`:
```
netbox_1    |   Applying virtualization.0002_virtualmachine_add_status... OK
netbox_1    |   Applying virtualization.0003_cluster_add_site... OK
netbox_1    |   Applying virtualization.0004_virtualmachine_add_role... OK
netbox_1    | 💡 Username: admin, E-Mail: admin@example.com
netbox_1    | ⚙️ Executing '/opt/netbox/startup_scripts/00_users.py'
netbox_1    | ⚙️ Executing '/opt/netbox/startup_scripts/10_groups.py'
netbox_1    | ⚙️ Executing '/opt/netbox/startup_scripts/20_custom_fields.py'
netbox_1    | Traceback (most recent call last):
netbox_1    |   File "./manage.py", line 10, in <module>
netbox_1    |     execute_from_command_line(sys.argv)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
netbox_1    |     utility.execute()
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
netbox_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
netbox_1    |     self.execute(*args, **cmd_options)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
netbox_1    |     output = self.handle(*args, **options)
netbox_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 101, in handle
netbox_1    |     exec(sys.stdin.read())
netbox_1    |   File "<string>", line 41, in <module>
netbox_1    | NameError: name 'CF_FILTER_CHOICES' is not defined
netboxdocker_netbox_1 exited with code 1
```

I _think_ the some step was overlooked while merging in PR #66.

BTW, the example for `selection_field_auto_weight` still appears to use the `filterable: true` format which has been deprecated. I didn't test that specifically, but just an FYI.

**Comment by thde** [comment]
You're right. Thanks for reporting :). A fix should be merged soon.
