### ISSUE TITLE
Issue with 'startup_scripts' in 'v2.4-beta1'

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#84]
## Current Behavior
Previously working development box when changed to use image `v2.4-beta1`, the following error occurs:
```
netbox_1    |   Applying virtualization.0004_virtualmachine_add_role... OK
netbox_1    |   Applying virtualization.0005_django2... OK
netbox_1    |   Applying virtualization.0006_tags... OK
netbox_1    |   Applying virtualization.0007_change_logging... OK
netbox_1    | � Username: admin, E-Mail: admin@example.com
netbox_1    | usage: manage.py shell [-h] [--version] [-v {0,1,2,3}] [--settings SETTINGS]
netbox_1    |                        [--pythonpath PYTHONPATH] [--traceback] [--no-color]
netbox_1    |                        [--no-startup] [-i {ipython,bpython,python}]
netbox_1    |                        [-c COMMAND]
netbox_1    | manage.py shell: error: unrecognized arguments: --plain
```

## Expected Behavior
To create `users`, `groups`, and `custom_fields` the same way that was done in previous versions.

## Debug Information

The output of `docker-compose version`: `1.16.1, build 6d1ac21`
The output of `docker version`: `18.01.0-ce`
The output of `git rev-parse HEAD`: `824141f587b8e49088264a07bda9bbc32040ef86`
The command you used to start the project: `docker-compose up -d`

The output of `docker-compose logs netbox`:
N/A - Relevant portion is above
If needed, I can include all logs upon request.

**Comment by bdlamprecht** [comment]
Apparently, this occurred due to changes in `Django` since version `1.10`.
See the documentation in the current v1 release of [django-admin](https://docs.djangoproject.com/en/1.11/ref/django-admin/#shell) documentation.

Since `v2.4` of `NetBox` only uses `Django 2`, this is why this error occurs.

I've looked into the code but I'm not sure where this code actually takes place to do a PR myself.
I'll keep looking, but thought I'd point out what I've found in the interim.

**Comment by bdlamprecht** [comment]
@sts It has been awhile since I dug into the details of `docker-compose`, so I apologize for this question in advance...

What **_else_** did you have to change to get the `build .` command to use to the `develop-2.4` branch of `NetBox`?

I changed the line `18` of the `Dockerfile` from `ARG BRANCH=master` to `ARG BRANCH=develop-2.4` and ran the same commands as you **mentioned** above, but for some reason, once the container runs, it still shows as `NetBox v2.3.6`.

Also, I've verified that I don't have **any** remnant images of `ninech/netbox` lying around, so I'm kind of frustrated.

**Comment by bdlamprecht** [comment]
Well, I figured it out.

I don't know what I did but I had to eventually split the `Dockerfile` into two separate parts and manually tag / use the images.  Nonetheless, it works.

I don't see a reason why this change couldn't get merged as it is actually supported in Django `1.10` and only becomes deprecated in `v2.4` of NetBox (which uses Django version `2.0`).

@sts Would you mind writing a PR and getting is submitted?

**Comment by sts** [comment]
Sorry I forgot to mention that I did an `export VERSION=v2.4-beta1` before running `docker-compose up` again.

**Comment by thde** [comment]
Thanks for catching that!
