### ISSUE TITLE
Problem with automated images on DockerHub

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#87]
## Current Behavior
Previously, following the "[Quickstart](https://github.com/ninech/netbox-docker#quickstart)" would automatically run the latest release of `NetBox` that had been released and tagged appropriately.

I'm assuming this process was automated, but as of just now, when following the the exact commands mentioned, it still launches `v2.3.7` instead of `v2.4.0` which was released yesterday.

A similar issue occurred with `v2.3.5` in issue #81, and I'm assuming it took the same took place with `v2.3.6` and `v2.3.7` as well (several days in delayed builds).

The automated builds occurred during the night (in eastern time) so that explains why `v2.4.1` which was released this morning hasn't been built and stored on `DockerHub` yet.

I understand the `ninech` is not related with the official releases of `NetBox` and is "hosting" it to help the greater community out, but I'm hoping it can be fixed to how it was before.

## Expected Behavior
To start the latest release of `NetBox` like was occurring previously somewhere around March 2018.

## Debug Information

The output of `docker-compose version`: `1.22.0`
The output of `docker version`: `18.01.0-ce`
The output of `git rev-parse HEAD`: `61dd958af4668c997716b54246f3ce260fbe8f5f`
The command you used to start the project: `docker-compose up -d`

The output of `docker-compose logs netbox`:
N/A - It starts fine, just not the current release.

**Comment by thde** [comment]
Hey @bdlamprecht, thanks for bringing this up!

Travis currently builds daily (it's not specified when and I won't be able to from the UI 🤔 ) with the following condition " Do not run if there has been a build in the last 24h".

We could definitely remove the condition so a new image should be out max. 24 hours later then a Netbox release. Could you live with that?

We're definitely open if you have an easier/simpler solution. But as it looks to me right now some sort of "push" to build the new image isn't worth the added complexity.

**Comment by bdlamprecht** [comment]
I'm not all that experienced _**yet**_ in the DevOps world so I can't speak to any other "easier/simpler solution.

Concerning this comment:
>We could definitely remove the condition so a new image should be out max. 24 hours later then a Netbox release. Could you live with that?

Yes, that would work fine for me.  Just as long as is tagged appropriately with the tags from the `NetBox` releases.

Thanks again!
