### ISSUE TITLE
Webhook Backend is not started

### ISSUE THREAD

**Issue by mweinelt** [ninech/netbox-docker#88]
## Current Behavior

Webhooks are configured but don't fire.

...

## Expected Behavior

Webhooks should fire.

...

## Debug Information

I'm running `v2.4.2-ldap` and the rqworker (webhook backend) is not being started.

See https://github.com/digitalocean/netbox/issues/2338

**Comment by f-breidenstein** [comment]
Can confirm the same behaviour for the non-ldap version of `v2.4.2` and the  `webhook-backend` images from DockerHub.

**Comment by cimnine** [comment]
`webhook-backend` build is irrelevant now since the webhook things have been merged into Netbox's main branch. The branch won't be built in the future.

I currently don't know why the webhooks don't fire and sadly have no resources to look into it.

**Comment by cimnine** [comment]
But https://github.com/digitalocean/netbox/issues/2338 seems to be a good place to start.

**Comment by mweinelt** [comment]
Yup, I referenced that issue in the top post.

**Comment by cimnine** [comment]
There's more to that. A redis will be required as well. See the updated installation instructions.

http://netbox.readthedocs.io/en/stable/installation/2-netbox/

**Comment by cimnine** [comment]
_I think_ in order to get this working, at least the following has to be altered:

* docker-compose.yml:
  * add redis container
  * add django-rq worker container (based on ninech/netbox-docker image, but different startup command)
* configuration.py:
  * add redis settings 
  * add webhook settings

**Comment by bdlamprecht** [comment]
I'm going to start working on this but want to be sure no one else is doing it as well?

@cimnine I'm going to assume you want to use a variant-based approach as well similar to way the `-ldap` build works.  Could you confirm that for me?

**Comment by mweinelt** [comment]
In that case we'd want a `-ldap-webhooks` variant x)

**Comment by bdlamprecht** [comment]
True, but I'd prefer to take it a step at a time

**Comment by bdlamprecht** [comment]
That works for me!

I just assumed since it was optional in the documentation for NetBox (similar to LDAP support), that is the direction you would take it.

Just to confirm, if I can get `webhooks` functional with just the `docker-compose.yml` file, I can expect it to me merged?

**Comment by cimnine** [comment]
The difference with LDAP is that it would need an LDAP server, and I believe most people don't want to manage that _just to run Netbox_. Which is different for the webhooks, as I'd say most people will want to at least try them out. And when it's pre-configured in a good way, than they don't need to touch anything as the docker-compose file will provide Redis and the worker.

**Comment by bdlamprecht** [comment]
This was done in PR #90 .
