### ISSUE TITLE
Enable Adding Specific Permissions to Users / Groups

### ISSUE THREAD

**Issue by bdlamprecht** [ninech/netbox-docker#92]
## Current Behavior
Currently, in the `initializers` directory there are YAML files which specify which groups and users need to be created if they don't already exist.  These are processed by the corresponding code in the `startup_scripts` directory.

However, there is no method to define _which_ `permissions` a group or user needs to have.
After communicating with @cimnine via NetworkToCode Slack, this was mentioned:

>So if you figure out how to assign permissions using the `./manage.py shell` of Netbox, then this could be added to the `startup_scripts` and the corresponding yaml structures can be extended.

In short, I've figured out how to do this as requested, but I'm not sure the appropriate way to code this up and "extend" the "yaml structures".

I'm posting working code against the `v2.4.3` release of NetBox here for reference.

```python
from django.contrib.auth.models import Permission, Group, User
from django.contrib.contenttypes.models import ContentType

from ipam.models import Aggregate
from dcim.models import Device

g = Group.objects.get(name='applications')
u = User.objects.get(username='technical_user')

group_ct = ContentType.objects.get_for_model(Aggregate)
user_ct = ContentType.objects.get_for_model(Device)

group_perm = Permission.objects.get(content_type=group_ct, codename='add_aggregate')
user_perm = Permission.objects.get(content_type=user_ct, codename='add_device')

g.permissions.add(group_perm)
u.user_permissions.add(user_perm)

g.save()
u.save()
```

Obviously, more work need to be done here, so I'm hoping someone else besides myself sees the need for this and can work on this more than I have the time to. Otherwise, I'll **slowly** figure out how to do so and make sure that it is implemented in a way that is beneficial for the whole community.

## Expected Behavior
N/A

## Debug Information
N/A

**Comment by bdlamprecht** [comment]
@cimnine Nice, glad to have this implemented!

**Comment by cimnine** [comment]
You will have to wait till next week though until it gets merged.

**Comment by bdlamprecht** [comment]
Yeah, no worries, after ~2 months I can wait an additional week. :smile:
