### ISSUE TITLE
Default Redis Port as Int not String

### ISSUE THREAD

**Issue by splattner** [ninech/netbox-docker#96]
https://github.com/ninech/netbox-docker/blob/968bb9f10fb6440cd319642037e71e0a678594a1/configuration/configuration.py#L149

The default Redis Port has to be an int not a String, otherwise connection to Redis fails. Setting this via Env is fine. 

`ValueError: invalid literal for int() with base 10: 'tcp://172.30.105.215:6379'`

**Comment by cimnine** [comment]
Thank you for reporting this issue!
